### ISSUE TITLE
Instant crash: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by schef** [FedeDP/ncursesFM#11]
Hello..
I'm using UpToDate Archlinux and wanted to try it out. Did make and make install and after that i had instant crash: Segmentation fault (core dumped)
What should i do?

**Comment by FedeDP** [comment]
Thanks for the reporting!
Can you please do this for me? It will help me solve the issue:  
- clone this repo
- cd ncursesFM
- make debug
- gdb ./ncursesFM  
  In gdb shell now:  
- "run"
- when it crashes, issue a "bt" and send me the output.

Thank you very much (hope this is clear...ask me whatever isn't!)

**Comment by schef** [comment]
```
#0  0x00007ffff6b6d0ac in vfprintf () from /usr/lib/libc.so.6
#1  0x00007ffff6b8c0bb in vsprintf () from /usr/lib/libc.so.6
#2  0x00007ffff6b72da7 in sprintf () from /usr/lib/libc.so.6
#3  0x000000000040e31b in change_unit (size=1.4421407, str=0x7fffffffe7a0 "1.44") at ui_functions.c:604
#4  0x000000000040a966 in add_device (dev=0x6fead0, name=0x6ac8c0 "/dev/sda6") at mount.c:700
#5  0x000000000040a190 in enumerate_block_devices () at mount.c:538
#6  0x0000000000409791 in start_monitor () at mount.c:290
#7  0x000000000040734d in set_pollfd () at main.c:147
#8  0x00000000004070fd in main (argc=1, argv=0x7fffffffe958) at main.c:78
```

**Comment by FedeDP** [comment]
Can you share with me your  
$ df -h  
and  
$ uname -a  
output?
Thanks!

**Comment by schef** [comment]
```
[schef@dellch ~]$ df -h
Filesystem      Size  Used Avail Use% Mounted on
dev             7.8G     0  7.8G   0% /dev
run             7.8G  776K  7.8G   1% /run
/dev/sda4        99G   21G   74G  22% /
tmpfs           7.8G  112K  7.8G   1% /dev/shm
tmpfs           7.8G     0  7.8G   0% /sys/fs/cgroup
tmpfs           7.8G  1.8M  7.8G   1% /tmp
/dev/sda6       1.5T  153G  1.2T  12% /home
tmpfs           1.6G   12K  1.6G   1% /run/user/1000
[schef@dellch ~]$ uname -a
Linux dellch 4.5.4-1-ARCH #1 SMP PREEMPT Wed May 11 22:21:28 CEST 2016 x86_64 GNU/Linux
```

**Comment by FedeDP** [comment]
Ok, asap i'll fix this (probably later in the afternoon) and i'll let you know, thanks again!

**Comment by schef** [comment]
Thanks..:)

**Comment by FedeDP** [comment]
It should be fixed right now :)

**Comment by schef** [comment]
Yes it works..:)
